### ISSUE TITLE
TypeError: an integer is required

### ISSUE THREAD

**Issue by n1k0** [mozilla-services/kinto-fxa#46] opened 2017-02-13 16:59 UTC
With this config:

```ini
# Created at Tue, 28 Jun 2016 10:19:33 +0200
# Using Kinto version 3.3.0.dev0


[server:main]
use = egg:waitress#main
host = 0.0.0.0
port = %(http_port)s


[app:main]
use = egg:kinto

#
# Backends.
#
# http://kinto.readthedocs.io/en/latest/configuration/settings.html#storage
#
kinto.storage_backend = kinto.core.storage.memory
kinto.storage_url = 
kinto.cache_backend = kinto.core.cache.memory
kinto.cache_url = 
kinto.permission_backend = kinto.core.permission.memory
kinto.permission_url = 

#
# Auth configuration.
#
# http://kinto.readthedocs.io/en/latest/configuration/settings.html#authentication
#
kinto.userid_hmac_secret = d4130ea05e280987e89ff5ae5e99a39ef76b831ee72c652a4985a38fbd61959a
multiauth.policies = basicauth
		     fxa

# kinto.readonly = false
# kinto.bucket_create_principals = system.Authenticated
# kinto.batch_max_requests = 25

#
# Experimental JSON-schema on collection
# kinto.experimental_collection_schema_validation = true

#
# Plugins
#
kinto.includes = kinto.plugins.default_bucket
                 kinto.plugins.admin
                 kinto_fxa
                 kinto_attachment

kinto.attachment.base_path = /tmp
kinto.attachment.base_url = "/attachments/"

# Firefox Accounts configuration.
#   These are working FxA credentials for localhost:8888
multiauth.policy.fxa.use = kinto_fxa.authentication.FxAOAuthAuthenticationPolicy
fxa-oauth.client_id = 61c3f791f740c19a
fxa-oauth.client_secret = b13739d8a905315314b09fb7b947aaeb62b47c6a4a5efb00c378fdecacd1e95e
fxa-oauth.oauth_uri = https://oauth-stable.dev.lcip.org/v1
fxa-oauth.requested_scope = profile kinto
fxa-oauth.required_scope = kinto
fxa-oauth.relier.enabled = true
fxa-oauth.webapp.authorized_domains = *
```

`make serve` raises this error:

```
  (...)
  File "/home/niko/work/kinto/kinto/core/__init__.py", line 173, in includeme
    config.include(app)
  File "/home/niko/work/kinto/.venv/local/lib/python2.7/site-packages/pyramid/config/__init__.py", line 800, in include
    c(configurator)
  File "/home/niko/work/kinto/.venv/local/lib/python2.7/site-packages/kinto_fxa/__init__.py", line 63, in includeme
    config.scan('kinto_fxa.views', **kwargs)
  File "/home/niko/work/kinto/.venv/local/lib/python2.7/site-packages/pyramid/config/__init__.py", line 976, in scan
    ignore=ignore)
  File "/home/niko/work/kinto/.venv/local/lib/python2.7/site-packages/venusian/__init__.py", line 205, in scan
    __import__(modname)
  File "/home/niko/work/kinto/.venv/local/lib/python2.7/site-packages/kinto_fxa/views/relier.py", line 51, in <module>
    class FxALoginQueryString(colander.MappingSchema):
  File "/home/niko/work/kinto/.venv/local/lib/python2.7/site-packages/kinto_fxa/views/relier.py", line 52, in FxALoginQueryString
    redirect = URL()
  File "/home/niko/work/kinto/kinto/core/resource/schema.py", line 26, in __init__
    warnings.warn(message, DeprecationWarning)
TypeError: an integer is required
Makefile:93: recipe for target 'migrate' failed
make: *** [migrate] Error 1

```

**Comment by gabisurita** [comment] 2017-02-13 20:25
Hmm. That's weird. It seems related to https://github.com/Kinto/kinto/pull/1054but I've tried and couldn't reproduce it with the same config. Which kinto/python version are you using?

**Comment by n1k0** [comment] 2017-02-13 22:19
Kinto 8ac43951e06e663b1b84a5d30ccc623c3f87b932
Python 2.7.12

**Comment by glasserc** [comment] 2017-02-14 14:20
This should be fixed now, right?

**Closed by glasserc** 2017-02-14 14:20 UTC
